version: '2'

volumes:
  database:

services:
  mysql:
    build:
      context: .
      dockerfile: './docker/mysql/Dockerfile'
    image: ${PROJECT_NAME}_mysql:${ENVIRONMENT}
    command:
      [
        '--character-set-server=utf8',
        '--collation-server=utf8_unicode_ci',
        '--default-authentication-plugin=mysql_native_password',
      ]
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql

  postfix:
    build:
      context: .
      dockerfile: './docker/postfix/Dockerfile'
    image: ${PROJECT_NAME}_postfix:${ENVIRONMENT}
    container_name: ${PROJECT_NAME}_postfix
    ports:
      - '25:25'
    environment:
      - DEBUG=1
      - MAIL_NAME=${MAIL_NAME}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - DOCKER_IP=${DOCKER_IP}

  node:
    build:
      context: .
      dockerfile: './docker/node/Dockerfile'
    image: ${PROJECT_NAME}_node:${ENVIRONMENT}
    container_name: ${PROJECT_NAME}_node
    working_dir: /var/www/project
    volumes:
      - ./src/node_modules:/var/www/project/node_modules
    volumes_from:
      - data

  data:
    build:
      context: .
      dockerfile: './docker/data/Dockerfile'
    image: ${PROJECT_NAME}_data:${ENVIRONMENT}
    container_name: ${PROJECT_NAME}_data
    volumes:
      - ./src:/var/www/project
      - .git:/var/www/project/.git
    environment:
      TZ: ${TIMEZONE}
    tty: true

  redis:
    build:
      context: .
      dockerfile: './docker/redis/Dockerfile'
    image: ${PROJECT_NAME}_redis:${ENVIRONMENT}
    container_name: ${PROJECT_NAME}_redis
    ports:
      - "6379:6379"
